original_dataset_folder : "Book OCR Data"

original_dataset_paths:
  images : "/img"
  labels : "/ann"
  meta : "/meta.json"

dataset_folder : "data"

dataset_paths:
  images: "/images"
  labels: "/labels"

splits:
  - "/train"
  - "/val"
  - "/test"

model_path: 'yolov5'

weights:
  exp1: '/runs/train/exp1/weights/best.pt'
  exp2: '/runs/train/exp2/weights/best.pt'
  exp3: '/runs/train/exp3/weights/best.pt'
  exp4: '/runs/train/exp4/weights/best.pt'
  exp5: '/runs/train/exp5/weights/best.pt'
  exp6: '/runs/train/exp6/weights/best.pt'
  exp7: '/runs/train/exp7/weights/best.pt'
  exp8: '/runs/train/exp8/weights/best.pt'
  exp9: '/runs/train/exp9/weights/best.pt'
  exp11: '/runs/train/exp11/weights/best.pt'

tests_pth:
  imgs: 'imgs'

uploads:
  imgs: 'uploads/'